"""Generate DATA_SOURCES.md from what was actually downloaded.

Statistics and licenses come from the `_aurum_meta.json` written by ml.ingest
(which records the Roboflow project metadata verbatim) and from
reports/dataset_stats.json. Nothing in the output is typed by hand, so the
document cannot drift from the data.

Usage:
    python scripts/gen_data_sources.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
RAW = ROOT / "data" / "raw"
REPORTS = ROOT / "reports"

from ml.labels import load_label_map  # noqa: E402


def main() -> int:
    lm = load_label_map()
    registry = yaml.safe_load((ROOT / "configs" / "datasets.yaml").read_text())
    stats_path = REPORTS / "dataset_stats.json"
    if not stats_path.exists():
        raise SystemExit("reports/dataset_stats.json missing — run ml.prepare first")
    stats = json.loads(stats_path.read_text())

    metas = []
    for entry in registry["roboflow"]:
        p = RAW / entry["key"] / "_aurum_meta.json"
        if p.exists():
            metas.append(json.loads(p.read_text()))

    L: list[str] = []
    add = L.append

    add("# Aurum Vision — Data Sources\n")
    add("Every dataset used to train **Aurum Vision v0.1**, with the license and")
    add("statistics reported by the source platform at download time.\n")
    add("> This file is generated by `python scripts/gen_data_sources.py` from")
    add("> `data/raw/*/_aurum_meta.json` (written verbatim from the Roboflow")
    add("> project metadata API) and `reports/dataset_stats.json`. The numbers are")
    add("> not transcribed by hand.\n")

    add("## Summary\n")
    tot_img = sum(m["images_downloaded"] for m in metas)
    kept = sum(v for v in stats["kept_source_labels"].values())
    dropped = sum(v for v in stats["dropped_source_labels"].values())
    add(f"- **{len(metas)} source datasets**, all from Roboflow Universe")
    add(f"- **{tot_img:,} images** downloaded (includes Roboflow's augmented copies)")
    add(f"- **{kept:,} annotations** mapped into Aurum classes; **{dropped:,}** explicitly dropped")
    add(f"- Final classes: **{', '.join(lm.classes)}**")
    lic = sorted({m["license"] for m in metas})
    add(f"- Licenses present: **{', '.join(lic)}**\n")

    add("## Datasets used\n")
    for m in metas:
        add(f"### {m['name']} (`{m['key']}`)\n")
        add("| field | value |")
        add("|---|---|")
        add(f"| Source URL | {m['url']} |")
        add(f"| Version pinned | v{m['version']} |")
        add(f"| License | **{m['license']}** |")
        add(f"| Project type | {m['type']} |")
        add(f"| Images (source reports) | {m['images_reported']:,} |")
        add(f"| Images (downloaded, incl. augmentation) | {m['images_downloaded']:,} |")
        add(f"| Export format | {m['export_format']} (YOLO txt) |")
        add(f"| Downloaded | {m['downloaded_at']} |")
        add("")
        cls = m.get("classes_reported") or {}
        mapped: dict[str, list[str]] = {}
        drops: list[str] = []
        for src, n in sorted(cls.items(), key=lambda kv: -kv[1]):
            a = lm.resolve(src)
            if a:
                mapped.setdefault(a, []).append(f"`{src}` ({n:,})")
            else:
                drops.append(f"`{src}` ({n:,})")
        if mapped:
            add("**Mapped into Aurum classes:**\n")
            for a in lm.classes:
                if a in mapped:
                    add(f"- **{a}** &larr; {', '.join(mapped[a])}")
            add("")
        if drops:
            add(f"**Dropped from this dataset:** {', '.join(drops)}\n")
        if m.get("note"):
            add(f"**Why included:** {m['note']}\n")

    add("## Datasets found and deliberately excluded\n")
    add("Recorded so the exclusion is reviewable rather than invisible.\n")
    for e in registry.get("excluded", []):
        add(f"- **`{e['project']}`** — {' '.join(e['reason'].split())}")
    add("")

    add("## Label normalization\n")
    add(
        f"The full map lives in `configs/aurum_labels.yaml` (version "
        f"{lm.version}). Matching is on a normalized key, so `RAM stick`, "
        f"`ram_stick` and `Ram-Stick` all resolve to the same alias.\n"
    )
    add("A source label must be either mapped or explicitly dropped with a")
    add("reason; an unreviewed label raises an error during preparation rather")
    add("than being silently discarded.\n")
    add("### Class definitions\n")
    for c in lm.classes:
        add(f"- **{c}** — {' '.join(lm.definitions.get(c, '').split())}")
    add("")
    add("### Annotations kept, by source label\n")
    add("| source label | annotations |")
    add("|---|---|")
    for k, v in list(stats["kept_source_labels"].items())[:25]:
        add(f"| `{k}` | {v:,} |")
    add("")
    add("### Annotations dropped, by source label\n")
    add("| source label | annotations | reason |")
    add("|---|---|---|")
    for k, v in list(stats["dropped_source_labels"].items())[:25]:
        reason = lm.drop_reason(k) or ""
        add(f"| `{k}` | {v:,} | {' '.join(reason.split())[:110]} |")
    add("")

    add("## Notable class decisions\n")
    add(
        "- **`gpu` was dropped despite being the largest available label "
        "(~2,800 instances).** In every source dataset a `gpu` is an assembled "
        "graphics card whose camera-facing surface is a cooler shroud, not an "
        "exposed board. Merging it into PCB would train the model that plastic "
        "shrouds are circuit boards and would corrupt PCB counts in batch records."
    )
    add(
        "- **`ic` was not merged into CPU.** An `IC` annotation covers every "
        "integrated circuit on a board — regulators, controllers, flash. Folding "
        "these into CPU would make the CPU count in a batch record meaningless."
    )
    add(
        "- **`ram_slot`, `gpu_slot` and `rear_io` were merged into Connector.** "
        "A DIMM socket, a PCIe socket and a rear port bank are all mating "
        "interfaces with plated contacts, and they are the only source of "
        "whole-object Connector boxes at a scale a webcam resolves."
    )
    add(
        "- **`battery` was considered as a fifth class and rejected.** The "
        "available annotations span 9V cells, coin cells, laptop packs and RC "
        "LiPo packs, which are not one visual category.\n"
    )

    add("## Splits and leakage control\n")
    g = stats["grouping"]
    add(
        f"- {g['images_hashed']:,} images hashed; {g['stem_groups']:,} source-stem "
        f"groups merged into **{g['clusters']:,} duplicate clusters** "
        f"({g['merges']} near-duplicate merges at Hamming ≤ {stats['hamming']})."
    )
    add(
        "- Splits are assigned over **clusters, never images**, so augmented "
        "copies and re-uploads of one photograph cannot straddle train and test."
    )
    add(
        f"- {stats['augmented_copies_dropped_from_heldout']:,} augmented copies "
        f"were removed from valid/test so held-out counts reflect unique scenes."
    )
    add(
        f"- {stats['background_images_dropped']:,} background-only images dropped "
        f"(capped so they cannot drown the labelled objects).\n"
    )
    add("| split | images | " + " | ".join(lm.classes) + " |")
    add("|---|---|" + "---|" * len(lm.classes))
    for s in ("train", "valid", "test"):
        d = stats["splits"][s]
        add(
            f"| {s} | {d['images']:,} | "
            + " | ".join(f"{d['boxes'].get(c, 0):,}" for c in lm.classes)
            + " |"
        )
    add("")
    add(
        "Verified by `python -m ml.validate`, which independently re-checks for "
        "cluster containment, exact duplicates and perceptual near-duplicates "
        "across splits. See `reports/dataset_validation.json`.\n"
    )

    add("## Attribution\n")
    add(
        "All datasets are used under their stated licenses. CC BY 4.0 sources "
        "require attribution; the table above records each project URL for that "
        "purpose. Aurum Vision redistributes no source imagery — "
        "`data/` is gitignored and rebuilt with `python -m ml.ingest`.\n"
    )

    out = ROOT / "DATA_SOURCES.md"
    out.write_text("\n".join(L))
    print(f"wrote {out.relative_to(ROOT)} ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
