"""Generate docs/model-card.md from the actual training and evaluation outputs.

Reads models/aurum_vision_v0_1_meta.json, reports/test_metrics.json,
reports/dataset_stats.json and reports/dataset_validation.json. If evaluation
has not run, the card says so rather than shipping blank or invented numbers.

Usage:
    python scripts/gen_model_card.py
"""

from __future__ import annotations

import csv
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
REPORTS = ROOT / "reports"
MODELS = ROOT / "models"


def main() -> int:
    meta_p = MODELS / "aurum_vision_v0_1_meta.json"
    test_p = REPORTS / "test_metrics.json"
    stats_p = REPORTS / "dataset_stats.json"
    val_p = REPORTS / "dataset_validation.json"

    if not stats_p.exists():
        raise SystemExit("reports/dataset_stats.json missing — run ml.prepare")
    stats = json.loads(stats_p.read_text())
    meta = json.loads(meta_p.read_text()) if meta_p.exists() else {}
    test = json.loads(test_p.read_text()) if test_p.exists() else None
    val = json.loads(val_p.read_text()) if val_p.exists() else {}

    classes = stats["classes"]
    L: list[str] = []
    add = L.append

    add(f"# Model Card — {meta.get('model_version', 'Aurum Vision v0.1')}\n")
    add("> Generated by `python scripts/gen_model_card.py` from the training and")
    add("> evaluation outputs. Every number below was produced by the pipeline.\n")

    # ---------------------------------------------------------------- summary
    add("## At a glance\n")
    add("| | |")
    add("|---|---|")
    add(f"| Version | **{meta.get('model_version', 'v0.1')}** |")
    add("| Task | Object detection (bounding boxes) |")
    add(
        f"| Architecture | {meta.get('architecture', 'yolo11n.pt')} (COCO-pretrained, fine-tuned) |"
    )
    add(f"| Framework | {meta.get('framework', 'ultralytics')} / torch {meta.get('torch', '—')} |")
    add(f"| Classes | {', '.join(classes)} |")
    add(f"| Input size | {meta.get('image_size', '—')} px |")
    add(f"| Trained | {meta.get('trained_at', '—')} |")
    add(f"| Weights | `{meta.get('weights', 'models/aurum_vision_v0_1_best.pt')}` |")
    art = meta.get("artifact") or {}
    if art.get("sha256"):
        # The digest is what ties every metric below to one specific file. A
        # filename does not: two runs produce the same name and different weights.
        add(f"| Artifact SHA-256 | `{art['sha256']}` |")
        add(f"| Artifact size | {art['size_bytes']:,} bytes |")
    add("")

    add(
        "**What it does.** Identifies and counts four visible e-waste component "
        "categories in RGB imagery at webcam speed.\n"
    )
    add(
        "**What it does not do.** It does not measure precious-metal content, "
        "purity or mass. RGB imagery cannot determine composition. Recovery "
        "figures anywhere downstream are estimates built from component counts "
        "and published reference yields, and are labelled as estimates.\n"
    )

    # ------------------------------------------------------------- intended use
    add("## Intended use\n")
    add(
        "- **In scope:** identifying which component categories are present at a "
        "point-of-collection bench, counting them, and producing a batch record "
        "for the Aurum valuation/ledger workflow."
    )
    add(
        "- **Out of scope:** assaying metal content; safety-critical sorting; "
        "any decision where a missed or hallucinated component causes harm; "
        "automated pricing without human review."
    )
    add("- **Users:** the Aurum prototype bench and its operators. Not a deployed product.\n")

    # ------------------------------------------------------------ training data
    add("## Training data\n")
    add(
        f"Six public Roboflow Universe datasets normalized into {len(classes)} "
        f"Aurum classes. Full provenance, licenses and per-dataset counts are in "
        f"[`dataset.md`](dataset.md).\n"
    )
    add("| split | images | " + " | ".join(classes) + " |")
    add("|---|---|" + "---|" * len(classes))
    for s in ("train", "valid", "test"):
        d = stats["splits"][s]
        add(
            f"| {s} | {d['images']:,} | "
            + " | ".join(f"{d['boxes'].get(c, 0):,}" for c in classes)
            + " |"
        )
    add("")
    g = stats["grouping"]
    survivors = (
        f" Of those, **{val['clusters']:,} carry the images kept in the final dataset**; "
        f"the remainder held only images removed by the background cap or by held-out "
        f"pruning."
        if val
        else ""
    )
    add(
        f"Splits are assigned over duplicate clusters, not individual images: "
        f"{g['images_hashed']:,} images were grouped by source stem and merged across "
        f"datasets by SHA-256 and perceptual hash into **{g['clusters']:,} clusters** "
        f"({g['merges']} near-duplicate merges). Held-out splits keep one image per "
        f"cluster.{survivors}\n"
    )
    if val:
        add("Independently verified by `python -m ml.validate`:\n")
        add(f"- clusters spanning splits: **{val.get('clusters_spanning_splits')}**")
        add(f"- exact duplicates across splits: **{val.get('exact_duplicates_across_splits')}**")
        add(
            f"- near-duplicates train↔held-out (Hamming ≤ "
            f"{val.get('hamming_threshold')}): **{val.get('near_duplicates_train_to_heldout')}**\n"
        )

    # -------------------------------------------------------------- training cfg
    add("## Training configuration\n")
    add("| setting | value |")
    add("|---|---|")
    for k, label in (
        ("architecture", "Base weights"),
        ("image_size", "Image size"),
        ("epochs_requested", "Epochs (max)"),
        ("batch", "Batch size"),
        ("seed", "Seed"),
        ("device", "Device"),
    ):
        add(f"| {label} | {meta.get(k, '—')} |")
    results = ROOT / "runs" / "aurum_vision_v0_1" / "results.csv"
    if results.exists():
        rows = list(csv.DictReader(results.open()))
        if rows:
            add(f"| Epochs actually run | {len(rows)} |")
    add("")
    add(
        "Transfer learning only — nothing trained from scratch. Augmentation is "
        "horizontal flip, ±15° rotation and restrained HSV jitter. **No vertical "
        "flip**: an upside-down memory module is not a thing the bench will ever "
        "see, and colour is real class signal (green board, gold contacts).\n"
    )

    # ------------------------------------------------------------------ metrics
    add("## Evaluation — held-out test split\n")
    if not test:
        add(
            "> **Not yet evaluated.** Run `python -m ml.evaluate` to populate "
            "this section. No figures are stated until it has.\n"
        )
    else:
        ov = test["metrics_overall"]
        add(
            f"Measured on **{test['n_images']} unseen images** "
            f"({sum(test['n_instances'].values()):,} instances) that share no "
            f"duplicate cluster with training data.\n"
        )
        add("| metric | value |")
        add("|---|---|")
        add(f"| Precision | **{ov['precision']:.3f}** |")
        add(f"| Recall | **{ov['recall']:.3f}** |")
        add(f"| mAP@50 | **{ov['mAP50']:.3f}** |")
        add(f"| mAP@50:95 | **{ov['mAP50_95']:.3f}** |")
        add("")
        add("### Per class\n")
        add("| class | test instances | precision | recall | mAP@50 | mAP@50:95 |")
        add("|---|---|---|---|---|---|")
        for c in classes:
            m = test["metrics_per_class"].get(c)
            n = test["n_instances"].get(c, 0)
            if m:
                add(
                    f"| {c} | {n} | {m['precision']:.3f} | {m['recall']:.3f} | "
                    f"{m['mAP50']:.3f} | {m['mAP50_95']:.3f} |"
                )
            else:
                add(f"| {c} | {n} | — | — | — | — |")
        add("")
        add(
            "Artifacts in `reports/`: `confusion_matrix.png`, "
            "`BoxPR_curve.png`, `BoxF1_curve.png`, and example predictions "
            "under `reports/test_predictions/{correct,failures}/` with ground "
            "truth in white and predictions in gold.\n"
        )

        worst = min(
            (c for c in classes if test["metrics_per_class"].get(c)),
            key=lambda c: test["metrics_per_class"][c]["mAP50"],
            default=None,
        )
        if worst:
            add(
                f"The weakest class is **{worst}** "
                f"(mAP@50 {test['metrics_per_class'][worst]['mAP50']:.3f}). "
                f"It has the fewest training instances and the widest visual "
                f"range in the source data.\n"
            )

    # ------------------------------------------------- external / generalization
    add("## Generalization — external images\n")
    ext_p = REPORTS / "realworld_summary.json"
    ext = json.loads(ext_p.read_text()) if ext_p.exists() else None
    if not ext:
        add("> **Not yet probed.** Run `python scripts/fetch_realworld.py` then")
        add("> `python -m ml.realworld --path data/realworld`.\n")
    else:
        hit = ext["n_images"] - ext["images_with_no_detection"]
        rate = 100 * hit / max(1, ext["n_images"])
        add(
            f"The held-out test set above shares its provenance with training — "
            f"same source projects, same photographers. To probe whether the "
            f"model survives a genuinely different camera, it was run over "
            f"**{ext['n_images']} CC-licensed photographs from Wikimedia "
            f"Commons**, verified by perceptual hash to have zero overlap with "
            f"training.\n"
        )
        add(
            "**These images carry no ground-truth boxes, so no accuracy figure "
            "can be computed from them.** What follows is detection behaviour.\n"
        )
        add("| | |")
        add("|---|---:|")
        add(f"| Images | {ext['n_images']} |")
        add(f"| Images with at least one detection | **{hit} ({rate:.0f}%)** |")
        for c in classes:
            add(f"| {c} detections | {ext['total_detections'].get(c, 0)} |")
        add("")
        dead = [
            c
            for c in classes
            if not ext["total_detections"].get(c)
            and (test or {}).get("metrics_per_class", {}).get(c, {})
            and test["metrics_per_class"][c]["mAP50"] > 0.5
        ]
        if dead and test:
            worst = ", ".join(
                f"**{c}** scores {test['metrics_per_class'][c]['mAP50']:.3f} "
                f"mAP@50 on the held-out test set and produces **zero** "
                f"detections here"
                for c in dead
            )
            add(
                f"This is the single most important limitation of the model. "
                f"{worst}. A class can sit near the top of a held-out benchmark "
                f"and still fail outright on photographs taken by someone else, "
                f"with different framing, lighting and working distance.\n"
            )
        add(
            "Read the test figures accordingly: they measure generalization "
            "across photographs of the same kind, not readiness for a scrap "
            "dealer's bench. Closing this gap requires images collected on a "
            "real bench, not threshold tuning. Full detail in "
            "[evaluation.md](evaluation.md).\n"
        )

    # --------------------------------------------------------------- limitations
    add("## Limitations and failure modes\n")
    add(
        "- **No composition sensing.** The model sees surfaces. It cannot tell a "
        "gold-plated connector from a tin-plated one of the same shape."
    )
    add(
        "- **Domain gap.** Training images are internet photography of PC "
        "hardware — product shots, build photos, teardowns. A scrap bench has "
        "different lighting, clutter and camera angles. Use "
        "`python -m ml.realworld` to measure this on your own photographs "
        "before relying on the model in the field."
    )
    add(
        "- **Connector is broad.** It spans DIMM sockets, PCIe slots, rear port "
        "banks and RC plugs. Breadth was accepted to get whole-object connector "
        "coverage at all; it costs precision."
    )
    add(
        "- **`gpu` is not a class.** Graphics cards are deliberately not mapped "
        "to PCB, because their camera-facing surface is a cooler shroud. A "
        "shrouded card in frame may go undetected — that is intended."
    )
    add(
        "- **Counting is per-frame detection, not tracking.** Stacked or "
        "occluding boards can undercount. The batch record uses a median over a "
        "frame window to suppress flicker, not to resolve occlusion."
    )
    add(
        "- **Small test set.** Per-class figures rest on tens of instances, so "
        "treat differences of a few points as noise.\n"
    )

    # ------------------------------------------------- material estimation
    add("## Material estimation\n")
    ref_path = ROOT / "configs" / "material_reference.yaml"
    ref = yaml.safe_load(ref_path.read_text()) if ref_path.exists() else {}
    enabled = bool((ref or {}).get("enabled"))
    n_ev = len((ref or {}).get("evidence") or [])
    gaps = sorted((ref or {}).get("gaps", {}).keys() - {"all_components"})
    recovery_on = bool(((ref or {}).get("recovery") or {}).get("available"))

    add(
        f"**Composition: {'ENABLED' if enabled else 'DISABLED'}** — "
        f"`configs/material_reference.yaml` holds {n_ev} cited evidence "
        f"{'record' if n_ev == 1 else 'records'}, each resolving to a paper in "
        "`docs/sources/material_sources.yaml`.\n"
    )
    add(
        f"**Recovery: {'ENABLED' if recovery_on else 'UNAVAILABLE'}** — a recovery "
        "factor is applied only where a source measured recovery from a feed "
        "matching what Aurum detected.\n"
    )
    add("**What the mechanism does.** Aurum's economic claim is that component")
    add("identity plus published reference composition gives an *estimated*")
    add("quantity of material present. The counts come from this model. The")
    add("composition figures do not — and cannot — come from an image.\n")
    add("**How it fails closed.** A detected class with no cited figure blocks")
    add("the whole estimate rather than contributing a silent zero, and")
    add('`app/batch.recovery_estimate()` then returns `{"available": false,')
    add('"reason": ...}` with no numeric field at all. Concentration-based')
    add("figures are additionally refused unless the batch carries a *measured*")
    add("mass, because multiplying a simulated weight by a real concentration")
    add("would produce an invented quantity that reads as measured.\n")
    no_data = sorted(
        cls
        for cls, spec in ((ref or {}).get("components") or {}).items()
        if not (spec["subtypes"].get(spec["default_subtype"], {}).get("composition") or {})
    )
    if no_data:
        add(
            f"**No composition data at all:** {', '.join(no_data)}. A batch containing "
            "one of these produces no estimate.\n"
        )
    if gaps:
        add(
            f"**Partial metal coverage:** {', '.join(gaps)} — per-class detail in "
            "`docs/material-reference.md`. Missing figures are stated, not estimated.\n"
        )
    add("Whatever its state, every response carries the disclaimer that the")
    add("figure is an estimate and that Aurum Vision does not measure")
    add("precious-metal content.\n")
    # ------------------------------------------------------------------ ethics
    add("## Claims discipline\n")
    add("The following must **not** be claimed on the basis of this model:\n")
    add(
        "- that it detects, measures or predicts gold, silver, copper, palladium "
        "or any other metal content"
    )
    add("- that it is production-ready or industrial-grade")
    add("- any accuracy figure not present in the table above")
    add("- that simulated load-cell readings are measurements\n")
    add(
        "What can be said: *Aurum Vision identifies and counts visible e-waste "
        "component categories in real time, establishing a machine-readable "
        "record of what physically entered the workflow.*\n"
    )

    add("## Reproduction\n")
    add(
        "See [`training.md`](training.md). The full chain is `ml.ingest` → "
        "`ml.prepare` → `ml.validate` → `ml.train` → `ml.evaluate`.\n"
    )

    out = ROOT / "docs" / "model-card.md"
    out.write_text("\n".join(L))
    print(
        f"wrote {out.relative_to(ROOT)} ({len(L)} lines)"
        + ("" if test else "  [evaluation pending]")
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
